<?php

namespace MainBundle\Repository;

/**
 * City
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class City extends \Doctrine\ORM\EntityRepository
{
}
