<?php

namespace MainBundle\Repository;

/**
 * CityPopulation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityPopulation extends \Doctrine\ORM\EntityRepository
{
}
