<?php

namespace MainBundle\Repository;

/**
 * Parameters
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Parameters extends \Doctrine\ORM\EntityRepository
{
}
