<?php

namespace MainBundle\Repository;



/**
 * People
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class People extends \Doctrine\ORM\EntityRepository
{
}
