<?php

namespace MainBundle\Repository;

/**
 * Race
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Race extends \Doctrine\ORM\EntityRepository
{
}
