<?php

namespace MainBundle\Repository;

/**
 * Regime
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Regime extends \Doctrine\ORM\EntityRepository
{
}
