<?php

namespace MainBundle\Repository;

/**
 * Religion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Religion extends \Doctrine\ORM\EntityRepository
{
}
