<?php

namespace MainBundle\Repository;

/**
 * Society
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Society extends \Doctrine\ORM\EntityRepository
{
}
