<?php

namespace MainBundle\Repository;

/**
 * Solar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Solar extends \Doctrine\ORM\EntityRepository
{
}
