<?php

namespace MainBundle\Repository;

/**
 * Technology
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Technology extends \Doctrine\ORM\EntityRepository
{
}
