<?php

namespace MapBundle\Repository;

/**
 * Area
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Area extends \Doctrine\ORM\EntityRepository
{
}
