<?php

namespace MapBundle\Repository;

/**
 * Planet
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Planet extends \Doctrine\ORM\EntityRepository
{
}
