<?php

namespace MapBundle\Repository;

/**
 * Region
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Region extends \Doctrine\ORM\EntityRepository
{
}
