<?php

namespace MapBundle\Repository;

/**
 * Solar
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Solar extends \Doctrine\ORM\EntityRepository
{

    public function getAllSolars(){
        $query = $this->createQueryBuilder('s')
            ->join('s.planet','p')
            ->join('p.region','r')
            ->getQuery();

        $solars = $query->getResult();

        return $solars;
    }
}
