main_connect:
    path:     /
    defaults: { _controller: MainBundle:Default:connect }

main_delete:
    path:     /delete
    defaults: { _controller: MainBundle:Default:deleteGameData }

main_dashboard:
    path:     /dashboard
    defaults: { _controller: MainBundle:Default:dashboard }

main_map:
    path:     /map
    defaults: { _controller: MainBundle:Default:map }

main_planet_dashboard:
    path:     /planetdashboard/{idSelectedPlanet}
    defaults: { _controller: MainBundle:Default:planetDashboard }

main_planet_dashboard_new:
    path:     /newplanet
    defaults: { _controller: MainBundle:Default:createPlanet }
